package com.sarathi.dataloadingmangement

const val KEY_HEADER_TYPE = "header_type"
const val KEY_HEADER_MOBILE = "header_type_mobile"
const val BLANK_STRING = ""
const val MISSION_TABLE_NAME = "mission_table"
const val ACTIVITY_TABLE_NAME = "activity_table"
const val TASK_TABLE_NAME = "task_table"
const val CONTENT_TABLE_NAME = "content_table"
const val NUDGE_GRANT_DATABASE = "NudgeGrantDatabase"
const val MISSION_LANGUAGE_TABLE_NAME = "mission_language_table"
const val ACTIVITY_CONFIG_TABLE_NAME = "activity_config_table"
const val CONTENT_CONFIG_TABLE_NAME = "content_config_table"
const val GRANT_CONFIG_TABLE_NAME = "grant_config_table"
const val ANSWER_TABLE = "ques_answer_table"
const val UI_CONFIG_TABLE_NAME = "ui_config_table"
const val ACTIVITY_LANGUAGE_ATTRIBUTE_TABLE_NAME = "activity_language_attribute_table"
const val ACTIVITY_CONFIG_LANGUAGE_ATTRIBUTE_TABLE_NAME = "activity_config_language_attribute_table"
const val TASK_ATTRIBUTE_TABLE_NAME = "task_attribute_table"
const val SUBJECT_ATTRIBUTE_TABLE_NAME = "subject_attribute_table"
const val ATTRIBUTE_VALUE_REFERENCE_ENTITY_TABLE_NAME = "attribute_value_reference_table"
const val SURVEY_TABLE = "survey_table"
const val SECTION_TABLE = "section_table"
const val QUESTION_TABLE = "question_table"
const val OPTION_TABLE = "option_table"
const val PROGRAMME_TABLE_NAME = "programme_table"
const val SUCCESS_CODE = "200"
