package com.nudge.core.enums

enum class AppConfigKeysEnum {
    SYNC_ENABLED,
    SYNC_ENABLED_V2,
    DATA_TAB_VISIBILITY,
    BLOB_IMAGE_UPLOAD_ENABLED,
    SYNC_BATCH_SIZE,
    SYNC_RETRY_COUNT,
    MIX_PANEL_KEY,
    AZURE_STORAGE_DETAIL,
    ENCODED_KEY,
    SELECTION_CONTAINER_NAME,
    POST_SELECTION_CONTAINER_NAME,
    USE_BASELINE_V1,
    SENSITIVE_INFO_KEY,
    SOFT_EVENT_LIMIT_THRESHOLD,
    HARD_EVENT_LIMIT_THRESHOLD,
    SYNC_CONSUMER_BAR_VISIBILITY
}
