package com.nrlm.baselinesurvey.utils

enum class PageFrom {
    SPLASH_PAGE,
    HOME_PAGE,
    VILLAGE_PAGE,
    DIDI_LIST_PAGE,
    SUMMARY_ONE_PAGE,
    SUMMARY_TWO_PAGE,
    SUMMARY_PAGE,
    VO_ENDORSEMENT_LIST_PAGE,
    VO_ENDORSEMENT_SUMMARY_PAGE,
    NOT_AVAILABLE_STEP_COMPLETE_PAGE,
    NOT_AVAILABLE_STEP_COMPLETE_CAMERA_PAGE,
    NOT_AVAILABLE_STEP_COMPLETE_SUMMARY_PAGE,
    DIDI_SCORE_LIST_PAGE
}