package com.sarathi.dataloadingmangement.util

const val KEY_HEADER_TYPE = "header_type"
const val KEY_HEADER_MOBILE = "header_type_mobile"
const val BLANK_STRING = ""
const val MISSION_TABLE_NAME = "mission_table"
const val MISSION_LANGUAGE_TABLE_NAME = "mission_language_table"
const val ACTIVITY_TABLE_NAME = "activity_table"
const val TASK_TABLE_NAME = "task_table"
const val ACTIVITY_CONFIG_TABLE_NAME = "activity_config_table"
const val CONTENT_CONFIG_TABLE_NAME = "content_config_table"
const val UI_CONFIG_TABLE_NAME = "ui_config_table"
const val ACTIVITY_LANGUAGE_ATTRIBUTE_TABLE_NAME = "activity_language_attribute_table"
const val ACTIVITY_CONFIG_LANGUAGE_ATTRIBUTE_TABLE_NAME = "activity_config_language_attribute_table"
const val TASK_ATTRIBUTE_TABLE_NAME = "task_attribute_table"
const val SUBJECT_ATTRIBUTE_TABLE_NAME = "subject_attribute_table"
const val ATTRIBUTE_VALUE_REFERENCE_ENTITY_TABLE_NAME = "attribute_value_reference_table"