package com.nudge.core

enum class EventSyncStatus(val eventSyncStatus: String) {
    OPEN("PRODUCER_OPEN"),
    PRODUCER_IN_PROGRESS("PRODUCER_IN-PROGRESS"),
    PRODUCER_RETRY("PRODUCER_RETRY"),
    PRODUCER_SUCCESS("PRODUCER_SUCCESS"),
    PRODUCER_FAILED("PRODUCER_FAILED"),
    CONSUMER_OPEN("CONSUMER_OPEN"),
    CONSUMER_IN_PROGRESS("CONSUMER_IN-PROGRESS"),
    CONSUMER_RETRY("CONSUMER_RETRY"),
    CONSUMER_SUCCESS("CONSUMER_SUCCESS"),
    CONSUMER_FAILED("CONSUMER_FAILED"),
    IMAGE_NOT_EXIST("IMAGE_NOT_EXIST"),
    BLOB_UPLOAD_FAILED("BLOB_UPLOAD_FAILED"),
    ERROR("ERROR")
}