package com.patsurvey.nudge.utils

enum class BPCVillageStatus {
    VO_ENDORSEMENT_NOT_STARTED,
    VO_ENDORSEMENT_IN_PROGRESS,
    VO_ENDORSEMENT_COMPLETED,
    BPC_VERIFICATION_NOT_STARTED,
    BPC_VERIFICATION_IN_PROGRESS,
    BPC_VERIFICATION_COMPLETED
}