package com.patsurvey.nudge.utils

enum class NumericQuestionsErrorEnum {
    NO_ERROR,
    TOTAL_FAMILY_MEMBER_LOW_LIMIT_ERROR,
    TOTAL_FAMILY_MEMBER_NOT_LESS_THAN_EARNING_MEMBER_ERROR,
    EARNING_MEMBERS_LOW_LIMIT_ERROR,
    EARNING_MEMBERS_NOT_MORE_THAN_FAMILY_MEMBER_ERROR,
    LOW_LIMIT
}