package com.nudge.core.database

import com.nudge.core.CASTE_TABLE
import com.nudge.core.LANGUAGE_TABLE_NAME
import com.nudge.core.TRANSLATION_CONFIG_TABLE_NAME


object MigrationQueries {
    val CREATE_CASTE_TABLE =
        "CREATE TABLE IF NOT EXISTS $CASTE_TABLE (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `casteId` INTEGER, `casteName` TEXT NOT NULL, `languageId` INTEGER NOT NULL, `languageCode` TEXT NOT NULL)"
    val CREATE_LANGUAGE_TABLE =
        "CREATE TABLE IF NOT EXISTS $LANGUAGE_TABLE_NAME (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `orderNumber` INTEGER NOT NULL, `language` TEXT NOT NULL, `langCode` TEXT, `localName` TEXT)"
    val CREATE_TRANSLATION_CONFIG_TABLE =
        "CREATE TABLE IF NOT EXISTS $TRANSLATION_CONFIG_TABLE_NAME (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, `userId` TEXT NOT NULL, `key` TEXT NOT NULL, `value` TEXT NOT NULL, `languageCode` TEXT NOT NULL)"
}

